name: Deploy

on:
  push:
    branches: [ main ]

jobs:
            
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
    - name: Executing remote ssh docker deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_MACHINE }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          cd /data/nginx-static
          git fetch && git pull
